### ISSUE TITLE
Please, tag versions and release a new version

### ISSUE THREAD

**Issue by eribertomota** [lmanul/gimp-texturize#2]
Dear developer,

I intent to maintain gimp-texturize in Debian. The package is currently orphan. Can you set tags in your source code, as 2.1 or v2.1, and release a new version (2.2)? I need it to control the packaging and upstream versions.

Regards,

Eriberto

**Comment by eribertomota** [comment]
Hello, any news?

**Comment by hellocatfood** [comment]
Probably best to fork it and do it yourself at this point

**Comment by eribertomota** [comment]
@hellocatfood I don't intent to maintain this project. I think is very easy for @lmanul set a tag to help the FOSS community.

**Comment by lmanul** [comment]
Sorry all for the delay!! I created a tag and release "2.2" and attached a compiled binary. I hope this helps, please let me know if I did this completely the wrong way :-D

**Comment by eribertomota** [comment]
This is the right way. For Debian, I need the source code only.

I was the maintainer of the gimp-texturize on Debian. I made the package orphan because it stop to work and I  had not communication with you. I will try the version 2.2 tomorrow.

**Comment by lmanul** [comment]
Great, my apologies for the delay, and thank you very much for your help @eribertomota  :-)

**Comment by eribertomota** [comment]
I am happy to see gimp-texturize alive again. Thanks for your work. If needed, tomorrow I will send PR or open bugs.
